# -*- coding: utf-8 -*-
"""Time_series_Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-spGlIOCWmpdCb5u55NJtuwteZENRlg
"""

# STEP 1: Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# STEP 2: Load Dataset

df = pd.read_csv('/content/Electric_Production.csv')

# Show first 5 rows
df.head()

# Dataset information

df.info()

# Check missing values
df.isnull().sum()

# Dataset information

df.info()

# Check missing values
df.isnull().sum()

# Rename columns

df.columns = ['Date', 'Production']

df.head()

# Convert Date column to datetime

df['Date'] = pd.to_datetime(df['Date'])

# Set Date as index
df.set_index('Date', inplace=True)

df.head()

# Plot data

plt.figure(figsize=(15,6))

plt.plot(df['Production'])

plt.title('Electric Production Over Time')
plt.xlabel('Date')
plt.ylabel('Production')

plt.show()

# Rolling Mean

rolling_mean = df['Production'].rolling(window=12).mean()

plt.figure(figsize=(15,6))

plt.plot(df['Production'], label='Original')
plt.plot(rolling_mean, label='Rolling Mean', color='red')

plt.legend()
plt.show()

# Split dataset

train_size = int(len(df) * 0.8)

train = df[:train_size]
test = df[train_size:]

print("Train Size:", len(train))
print("Test Size:", len(test))

!pip install pmdarima

from statsmodels.tsa.arima.model import ARIMA

# Build model

model = ARIMA(train['Production'], order=(5,1,0))

model_fit = model.fit()

print(model_fit.summary())

# Forecast

forecast = model_fit.forecast(steps=len(test))

forecast

# Plot forecast

plt.figure(figsize=(15,6))

plt.plot(test.index, test['Production'], label='Actual')
plt.plot(test.index, forecast, label='Predicted', color='red')

plt.legend()

plt.title('Demand Forecasting')

plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(test['Production'], forecast)

rmse = np.sqrt(mean_squared_error(test['Production'], forecast))

print("MAE:", mae)
print("RMSE:", rmse)

import pickle

# Save model

with open('forecast_model.pkl', 'wb') as file:
    pickle.dump(model_fit, file)

print("Model Saved Successfully")

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import pickle
# from statsmodels.tsa.arima.model import ARIMA
# 
# # Title
# 
# st.title("⚡ Electric Production Forecast Dashboard")
# 
# # Load dataset
# 
# df = pd.read_csv("Electric_Production.csv")
# 
# # Rename columns
# 
# df.columns = ['Date', 'Production']
# 
# # Convert date column
# 
# df['Date'] = pd.to_datetime(df['Date'])
# 
# # Set index
# 
# df.set_index('Date', inplace=True)
# 
# # Show dataset
# 
# st.subheader("Dataset")
# 
# st.write(df.head())
# 
# # Plot original data
# 
# st.subheader("Production Trend")
# 
# fig, ax = plt.subplots(figsize=(12,5))
# 
# ax.plot(df.index, df['Production'])
# 
# plt.xlabel("Date")
# plt.ylabel("Production")
# 
# st.pyplot(fig)
# 
# # Load model
# 
# with open('forecast_model.pkl', 'rb') as file:
#     model = pickle.load(file)
# 
# # Forecast future values
# 
# forecast_steps = st.slider("Select Forecast Days", 1, 50, 12)
# 
# forecast = model.forecast(steps=forecast_steps)
# 
# # Create future dates
# 
# future_dates = pd.date_range(
#     start=df.index[-1],
#     periods=forecast_steps + 1,
#     freq='M'
# )[1:]
# 
# forecast_df = pd.DataFrame({
#     'Date': future_dates,
#     'Forecast': forecast
# })
# 
# # Show forecast table
# 
# st.subheader("Forecast Data")
# 
# st.write(forecast_df)
# 
# # Plot forecast
# 
# st.subheader("Forecast Plot")
# 
# fig2, ax2 = plt.subplots(figsize=(12,5))
# 
# ax2.plot(df.index, df['Production'], label='Historical Data')
# 
# ax2.plot(
#     forecast_df['Date'],
#     forecast_df['Forecast'],
#     label='Forecast',
#     color='red'
# )
# 
# plt.legend()
# 
# st.pyplot(fig2)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pandas
# numpy
# matplotlib
# statsmodels
# scikit-learn

